name: Update Data Files

on:
  schedule:
    # 每天UTC时间3点运行 (对应北京时间11点)
    - cron: '0 3 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update-data-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run update data files script
        id: update-files
        run: |
          node scripts/update-data-files.js
          # 检查文件是否有变更
          if [[ -n $(git status -s | grep "public/master_bk") ]]; then
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit changes if any
        if: steps.update-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/master_bk/
          git commit -m "Update master.json and cells.json data files [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 